name: agrovision
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.1.1
  fl_chart: ^0.66.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  sqflite: ^2.3.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/sql/agrovision_database.sql
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# --- Splash Screen Configuration ---
flutter_native_splash:
  color: "#4CAF50"
  android_12:
    color: "#4CAF50"
  # To use a logo, add it to assets/images/logo.png and uncomment the line below.
  # image: assets/images/logo.png
